### ISSUE TITLE
介绍C#的页面链接里疑似需要urlencode成C%23，否则#会被浏览器截断

### ISSUE THREAD

**Issue by lidh15** [gonglei007/GameDevMind#19]
![image](https://user-images.githubusercontent.com/14806954/228905350-5fc6ec9d-d234-4fd8-addd-1461582c3e31.png)
在这个页面点击C#语言链接，浏览器地址栏可以看到：
![image](https://user-images.githubusercontent.com/14806954/228905553-d9f8cba9-daa5-4c42-82d9-d5de70bfeab4.png)

![image](https://user-images.githubusercontent.com/14806954/228905702-788dc9c0-a3a7-46f3-bcbe-6446f1cf2ab8.png)=
而在这个页面点击C#语言链接，浏览器地址栏会截断导致404：
![image](https://user-images.githubusercontent.com/14806954/228906036-04adb207-b0e2-48bb-8b93-8f81cf3ca2b7.png)

**Comment by gonglei007** [comment]
感谢你的反馈，刚刚已经处理了。
